server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: efe
    password: 123
#  zipkin:
#    enabled: true
#    base-url: http://localhost:9411
#    service:
#      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/Java9TahminDB
  jpa:
    hibernate:
      ddl-auto: update
# ÖNEMLİ: Şifre gibi başkalarının görmesini istemeyeceğiniz verileri yml dosyasında dahi tutmak sakıncalıdır.
# Bu nedenle bu tür bilgilerin gizlenmesi gereklidir.
# Bu gizleme işlemi için Environment'lar(Ortam değişkenleri) kullanılmalıdır.
#authservices:
#  secrets:
#    secret-key: ${JAVA9_SECRETKEY}
#    issuer: ${JAVA9_ISSUER}